### ISSUE TITLE
Make notebooks easily executable

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy-tutorials#10]
We agreed at the [8 June 20 doc team meeting](https://hackmd.io/oB_boakvRqKR-_2jRV-Qjg#Notes-from-8-June-20) that interactivity is a vital feature of notebooks.

To ensure this, each tutorial will include:

1. A button to run the notebook in **Binder**
1. Also a button to run the notebook in **Colab**. Although we'd prefer that users choose Binder, Colab runs more quickly. We'd give users a choice.
1.  A button to easily **download** the notebook for local execution.

Per @rossbar all three of these can be included.

Noting this here as a requirement for new notebooks.

**Comment by melissawm** [comment]
With the new format for the repository, I think this is more or less solved. The only remaining question is whether we should have a colab link. Personally, I think Binder fits our project better.

**Comment by rgommers** [comment]
> Personally, I think Binder fits our project better.

I agree, I'd prefer to support the community-developed solution here. We don't need GPUs, so Binder fits the need - the slightly faster startup for me is not a good reason to add Colab.

Related: the second tutorial in this repo has "Colab" in the name in the README - that looks weird.
