### ISSUE TITLE
Indonesian translation for the documentation tutorials?

### ISSUE THREAD

**Issue by gitsava** [numpy/numpy-tutorials#109]
Can I change or add the language in the existing document toturial to Indonesian? Because I come from Indonesia. Thank you

**Comment by rgommers** [comment]
Hi @gitsava, thanks for asking! We have started to work on translations, but for the time being those are limited to the https://numpy.org website (see https://github.com/numpy/numpy/wiki/Translations-of-the-NumPy-website). We are not quite ready to start translating tutorials.

**Comment by rossbar** [comment]
I will close this now that the translation policy is explicit in the README (#113).
