### ISSUE TITLE
Question: Will the quickstart/absolute beginners tutorial be moved here?

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy-tutorials#12]
I was wondering if there was a long-term plan in place to move *all* of the tutorial material to this repo, including the tutorials that are already a part of the official NumPy documentation? I couldn't tell from NEP 44 if there were any concrete plans on this front yet.

**Comment by rgommers** [comment]
No, that's not the plan. This repo is meant to make it easier to contribute new material, not to move away from Sphinx completely.

**Comment by melissawm** [comment]
I agree, I think this is meant to host new contributions. On the other hand, if the community thinks having a jupyter notebook version of the Absolute Beginners tutorial here is good, I would not be against it.

**Comment by melissawm** [comment]
I'm closing this as I think the question has been answered, feel free to reopen if necessary.

**Comment by rossbar** [comment]
Oops, I had forgotten about this - 

The main reason I was thinking about this was that it could remove some of the doc-building CI burden from the numpy docs to the numpy-tutorials repo. I had been thinking of setting up the CI to make use of `jupyter-cache` which could then be used to only build notebooks that had been modified in any given PR. There would be an obvious advantage to doing so as the number of tutorials grows.

Note also that it wouldn't have been necessary to change the format from `.rst` to notebooks - the sphinx-based configuration would handle all input formats; however, with #17 this would no longer be true.

Anyways - none of this is very relevant anymore with `numpy-tutorials` heading in a non-sphinx direction, so it can stay closed. Just wanted to expand a little on my thought process (sorry I was tardy in doing so)!
