### ISSUE TITLE
Make sure the `random.Generator` interface is used in all tutorials

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy-tutorials#121]
The tutorials should use the recommended `random.Generator` interface for random number generation. A quick `grep` shows that there are some instances of the older usage in the following files:
 - tutorial-nlp-from-scratch.md
 - text_preprocessing.py

It would be a nice improvement to replace these instances with the recommended random interface.

**Comment by willhoh** [comment]
May I work on that? I used numpy in some tutorials and only in vs-code on simple python files. However, I would like to take on this task to maybe get an introduction to Jupiter Notebooks, but especially to learn how to contribute to open-source software.

**Comment by Mukulikaa** [comment]
@willhoh, NumPy doesn't assign issues so go ahead! Feel free to ping if you need any help.
