### ISSUE TITLE
MAINT: Remove explicit sphinx pin from environment.yml

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy-tutorials#138]
As of the time of posting, the conda environment resolution is not working properly. I suspect there is a packaging problem w/ dependency pinning on conda-forge (unproven).

This issue is a reminder to periodically remove the pin by reverting #136 in the future to test whether the problem has been fixed upstream. Once the conda CI job is green again without the pin, we can merge the reversion. See #136 for details.

**Comment by bsipocz** [comment]
Closed by #181
