### ISSUE TITLE
Issue on page /index.html

### ISSUE THREAD

**Issue by NiuJun-1015** [numpy/numpy-tutorials#149]
when I run my script, the error comes up, does Numpy 1.22.3 is not compatible for the previous vesion.(the script can work with numpy 1.21.5)

PS E:\Revo3.0\Py_Revo3.0\py_scripts> & E:/anaconda3/envs/myenv/python.exe e:/Revo3.0/Py_Revo3.0/py_scripts/Spotfire_IFR90_Parse_grpby.py
E:\anaconda3\envs\myenv\Lib\site-packages\numpy\__init__.py:142: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "e:\Revo3.0\Py_Revo3.0\py_scripts\Spotfire_IFR90_Parse_grpby.py", line 8, in <module>
    import pandas as pd
  File "E:\anaconda3\envs\myenv\Lib\site-packages\pandas\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "E:\anaconda3\envs\myenv\python.exe"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: 找不到指定的模块。

**Comment by rossbar** [comment]
This looks like an installation issue on windows - the traceback is pretty clear that it's an issue initializing mkl.

It's not clear to me how this was hit by the tutorials though... the traceback starts Python scripts that are unrelated to the tutorials. Did you perhaps intend to open this issue elsewhere? What set of commands gave you this error?

**Comment by rossbar** [comment]
I'm almost certain this is an env/installation issue, not something having to do with the tutorials specifically, therefore I will close this one.

@NiuJun-1015 if you are still having problems and think it's related to building the site, please feel free to reopen and provide additional info on 1) how you set up your environment and 2) what commands you used to trigger the above error.
