### ISSUE TITLE
INF: remove reviewNB app

### ISSUE THREAD

**Issue by bsipocz** [numpy/numpy-tutorials#187]
Github currently provides the same, or very similar functionality for notebooks in PRs. Do we know about any extra the app does as opposed the github review?

I've asked about this on slack, but open this issue here in case someone feels strongly about keeping reviewNB and wants to chime in before I remove the app.

**Comment by rossbar** [comment]
No, please remove it - this is left over from before we switched to the executablebooks workflow!

**Comment by bsipocz** [comment]
OK, I believe it's done by uninstalling it from GitHub Apps.
