### ISSUE TITLE
Issue on page /content/tutorial-svd.html

### ISSUE THREAD

**Issue by jerm40986** [numpy/numpy-tutorials#192]
Your issue content here.

**Comment by andyfaff** [comment]
Please don't open issues without content.

**Comment by melissawm** [comment]
Hello @jerm40986 - I am not sure what you were looking for with opening these issues in this repo, but I'd ask that you check your workflow and verify that you are not opening empty issues. If you need help with something or have suggestions, let us know as a comment here. Thanks
