### ISSUE TITLE
Add reviewnb to repo

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy-tutorials#2]
[ReviewNB](https://www.reviewnb.com/) is a nice tool for doing smart diffs of Jupyter notebooks, and it is free for open source projects (https://github.com/marketplace/review-notebook-app).

**Comment by rgommers** [comment]
Done! Let's test it:)

**Comment by rgommers** [comment]
Some intro email I got from ReviewNB also pointed out https://github.com/reviewNB/treon which looks potentially useful.

**Comment by rgommers** [comment]
I'll open a new issue for CI
