### ISSUE TITLE
Broken Binder ? 

### ISSUE THREAD

**Issue by Carreau** [numpy/numpy-tutorials#216]
Clicking on the binder-launch button leads to the raw md files from the notebooks. I'm guessing jupytext is not installed on the binder.

**Comment by Carreau** [comment]
Maybe that's due to recent changes @melissawm might know.

**Comment by bsipocz** [comment]
No surprises here, eventually everything, that is not tested, breaks: https://github.com/numpy/numpy-tutorials/issues/159
