### ISSUE TITLE
BUG: Suggest Edit button doesn't work on all pages

### ISSUE THREAD

**Issue by LiamConnors** [numpy/numpy-tutorials#229]
The **Suggest Edit** button only works on index pages that are in https://github.com/numpy/numpy-tutorials/tree/main/site

<img width="700" alt="image" src="https://github.com/user-attachments/assets/266786a5-ba29-41f8-88e2-7e7db4ff3b62">

So it won't work on this page: https://numpy.org/numpy-tutorials/content/tutorial-svd.html

It throws a 404.

It seems maybe the symbolic link to content in https://github.com/numpy/numpy-tutorials/tree/main/site doesn't work for the link for **Suggest Edit**.

Couldn't think of a solution other than moving content around, but happy to look further.

**Comment by bsipocz** [comment]
Thanks for the time reporting the issue.

While it was opened later, #231 has some more info, so I'm closing this a duplicate now.

**Comment by negativenagesh** [comment]
> Thanks for the time reporting the issue.
> 
> While it was opened later, #231 has some more info, so I'm closing this a duplicate now.

I'm new to Open Source..

But Thank You for the mention (https://github.com/numpy/numpy-tutorials/issues/231) @bsipocz
