### ISSUE TITLE
Add CI job that covers notebook content

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy-tutorials#3]
https://github.com/reviewNB/treon could work as the tool to validate notebook, it looks like it has extra features like running examples as doctests that could be useful.

The basic "run a notebook" is `jupyter nbconvert --to notebook --inplace --execute somenotebook.ipynb`.

I don't know what CI setups other projects use.

**Comment by melissawm** [comment]
treon currently does not support pytest; on the other hand, https://nbval.readthedocs.io/en/latest/ seems pretty complete (and in active development). It includes directives to skip the execution of certain cells, and for skipping comparison of specific outputs (such as images) and checking exceptions.
