### ISSUE TITLE
Activate CircleCI

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy-tutorials#40]
This is a follow-up to #36. 

cc @rossbar

**Comment by rossbar** [comment]
Okay, I've deactivated CircleCI on my fork.

Unfortunately I was wrong - I don't have org-wide permissions for numpy on CircleCI, only for `numpy/numpy`.

To activate circleCI for this repo, someone with admin privileges will have to go to: https://app.circleci.com/projects/project-dashboard/github/numpy and click `Follow Project` for `numpy-tutorials`. Ping @mattip @charris , who might have the appropriate circleci privileges.

**Comment by mattip** [comment]
I am not an admin here

**Comment by rgommers** [comment]
Activated, it's building now: https://app.circleci.com/pipelines/github/numpy/numpy-tutorials/1/workflows/b8f8a6a5-a01c-46a6-addc-dff2f8b89178/jobs/1

**Comment by rossbar** [comment]
Okay, things should be working now. Configuration has been modified (via the circleci web app) to allow running workflows from other forks so now the build workflow should run when PRs are opened/new pushes.

We still have to add a workflow to deploy the site via `gh-pages`, but that's a separate task.
