### ISSUE TITLE
Check out online rendering of notebooks (i.e. Binder)

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy-tutorials#5]
It's important to make the notebooks easily executable online. It would be preferable to do it via [mybinder.org](https://mybinder.org/) unless there are performance issues (for example, if the notebooks take too long to render).

**Comment by bjnath** [comment]
I suggest renaming this issue to "Support rendering of notebooks", so we can also discuss features that enable easy downloading to run the notebook locally.

**Comment by melissawm** [comment]
I think both are covered in #17 .
