### ISSUE TITLE
Proposal: Static Equilibrium with NumPy

### ISSUE THREAD

**Issue by h2o-DS** [numpy/numpy-tutorials#55]
I have made a NumPy tutorial with Ryan Cooper that teaches static equilibrium with NumPy matrix manipulation. This primarily involves beams and cables. The tutorial is ready to be submitted.

**Comment by rossbar** [comment]
Very cool, thanks @h2o-DS ! If you've already generated the tutorial, please feel free to open a PR so we can take a detailed look :+1:

**Comment by melissawm** [comment]
Thank you, @h2o-DS ! I'll take a look at the PR later today - sorry for the delay!

**Comment by melissawm** [comment]
Closed via #61
