### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy-tutorials#6]
The docs team had a discussion about this and figured that we might want to change the repo name so it can also contain how tos, instead of just tutorials. Suggestions included

- `numpy-cookbook`: will this clash with [SciPy Cookbook](https://scipy-cookbook.readthedocs.io/)?
- `numpy-recipes`: this might be an alternative that avoids confusion with the existing `SciPy Cookbook` project.

cc @rossbar @bjnath

**Comment by rossbar** [comment]
These seem like nice ideas - I don't really have a strong feeling for anything in particular.

Re: the scipy cookbook - it would be nice if we could get some clarity on the status of that project and whether it's actively maintained and, if not, whether more attention would be welcome. There's a whole "chapter" dedicated to NumPy, but (with two exceptions) the "recipes" are over a decade old. That's not to say they're not valuable, but just an indication that they probably haven't received any attention in a while!

**Comment by bjnath** [comment]
@rossbar  That was my understanding too from later in the call when we talked about uniting the doc efforts of at least some of the numeric Python projects.  I've opened issue #9 for this thread.

**Comment by bsipocz** [comment]
If the rename still on the table or shall we close this issue now?

**Comment by rossbar** [comment]
I think there's enough inertia at this point that it's safe to close!
