### ISSUE TITLE
Joint cookbook with other scientific Python projects

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy-tutorials#9]
In #6  @rossbar writes:

> Re: the scipy cookbook - it would be nice if we could get some clarity on the status of that project and whether it's actively maintained and, if not, whether more attention would be welcome.

That was my understanding too, from later in the call when we talked about uniting doc efforts in the scientific Python community. @melissawm had the great idea of using SciPy Cookbook as a starting point. 

The first step would indeed be to sound out SciPy. We'd propose updating the content, rewriting it as notebooks, and presenting the Cookbook as a joint NumPy/SciPi resource.

Cookbooks are a natural intersection of projects, so it's likely that as other scientific Python projects learn of it they'll want to opt in, making it a community resource of growing value.

Clearly there are questions of governance, of where on the Internet it should go, and so on. 

For instance, do we continue in the original Cookbook model of user-contributed content or does somebody (who?) review PRs? A new project might want to use the Cookbook to show off a use case. This is both great and not so great, because the project might not be stable or long-lived. 

I'd volunteer to get things moving. But we have at least one doc meeting's worth of discussion before we go public.

**Comment by bjnath** [comment]
> numpy-recipes: this might be an alternative that avoids confusion with the existing SciPy Cookbook project.

We could call the joint site...ReciPy. (Just joking; it needs to be a little more specific.)

(As you might imagine, that name's already occurred to [somebody else](https://github.com/recipy/recipy).)

**Comment by pv** [comment]
FWIW, SciPy Cookbook is already in notebook format. Some of them have "supplementary files", which however should be copypasted into the notebooks. The issue is filtering out or updating content that's no longer relevant (many entries are > 10 years old). If a revised site is created, the Cookbook could as well be retired.

**Comment by bjnath** [comment]
>  SciPy Cookbook is already in notebook format

And it looks like much of that work was done by you! Thank you, and thanks for pointing it out.

**Comment by melissawm** [comment]
That sounds good to me, feel free to close or link the issues together @bsipocz !

**Comment by bsipocz** [comment]
OK, I'm linking the scipy lecture notes here as the place for the more ecosystem wide cookbooks/tutorials/etc.: https://github.com/scipy-lectures/scipy-lecture-notes
