### ISSUE TITLE
Proposal - Plotting Fractals

### ISSUE THREAD

**Issue by MichaelRipa** [numpy/numpy-tutorials#92]
Hi NumPy Devs,

I have mostly finished writing a tutorial called "Plotting Fractals", which teaches the basics of what fractals are and how to begin creating fractal images. I know that there are many fractal tutorials out there, so I tried making mine slightly different and appropriate for NumPy in the following ways:

- I tried explaining what fractals are through demonstration, which I think flows nicely with the tutorial style of writing.
- I used Universal Functions and Boolean Indexing in the tutorial and touched on how they helped speed up the computations.
- I included a large number of different fractals, including generalizations of the Mandelbrot set, Newton fractals and some "new" ones I made up.
- I provide guidance on "finding new fractals" through experimenting with different combinations of Universal Functions and by playing with the parameters.

If this is a topic of interest, I would be happy to submit a pull request of my work once I finish (which will likely be over the next couple days). 

Thanks for your time

Michael

**Comment by melissawm** [comment]
Hello, @MichaelRipa !

This sounds great - thanks for offering! Please feel free to submit a PR, and if you need guidance check our [style guide](https://github.com/numpy/numpy-tutorials/blob/main/content/tutorial-style-guide.md). I'm also happy to answer any specific questions you might have.

I might also ask you to give us feedback about our contributing docs - if you find that something is unclear, confusing or incomplete, please let us know. Cheers!

**Comment by MichaelRipa** [comment]
Thanks a lot for your reply @melissawm !  

I'll make sure to thoroughly review the style guide before submitting, and will reach out if I have any questions. Will also provide feedback if I notice anything (I have been nothing but impressed with the contributing docs thus far).

Michael
