### ISSUE TITLE
Alt-text sprint 2021-08-21

### ISSUE THREAD

**Issue by cooperrc** [numpy/numpy-tutorials#96]
This task list was started on 2021-08-21 for an alt-text code sprint. We can check off tutorials as the alt-text is added to the images. 

## NumPy Features
- [ ] Linear algebra on n-dimensional arrays
- [ ] Saving and sharing your NumPy arrays
- [ ] Masked Arrays
## NumPy Applications
- [x] Determining Moore’s Law with real data in NumPy
- [x] Deep learning on MNIST
- [ ] Deep reinforcement learning with Pong from pixels
- [x] X-ray image processing
- [ ] Determining Static Equilibrium in NumPy
Contributing
Why Jupyter Notebooks?

**Comment by peytondmurray** [comment]
I'll take x-rays!

**Comment by meghanrjones** [comment]
I'll add alt text to /content/tutorial-style-guide.md

**Comment by isabela-pf** [comment]
I'll add alt text to Moore's law!

**Comment by cooperrc** [comment]
Just submitted PR #100 for the alt-text in the MNIST tutorial. 

@isabela-pf, any thoughts on "captioning" matplotlib figures? I used italics, because I use that in technical reports here-and-there, but is there a better/more inclusive caption in-place of alt-text?

**Comment by peytondmurray** [comment]
Just submitted PR https://github.com/numpy/numpy-tutorials/pull/101 for the x-rays tutorial!

**Comment by rossbar** [comment]
I believe this was a tracking issue for a sprint that has concluded, so I will go ahead and close this. Accessbility improvements are of course always welcome!
